# Generated by Django 4.2.25 on 2025-11-23 20:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
