# Generated by Django 4.2.25 on 2025-12-03 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_company_alter_customuser_company_role_and_more'),
        ('sales', '0003_alter_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='users.company', verbose_name='Empresa'),
        ),
    ]
