# Generated by Django 4.2.25 on 2025-12-03 01:20

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_instock_admin',
            field=models.BooleanField(default=False, verbose_name='Admin InStock'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='Deve trocar senha'),
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nome completo')),
                ('personal_email', models.EmailField(max_length=254, verbose_name='Email pessoal')),
                ('company_name', models.CharField(max_length=150, verbose_name='Nome da empresa')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Mensagem')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=20)),
                ('generated_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email gerado')),
                ('generated_password', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de Acesso',
                'verbose_name_plural': 'Solicitações de Acesso',
                'ordering': ['-created_at'],
            },
        ),
    ]
