# Generated by Django 4.2.25 on 2025-12-03 21:39

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0008_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nome da Empresa')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email corporativo')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome da Empresa (legado)'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('admin', 'Administrador'), ('manager', 'Gerente'), ('operator', 'Operador'), ('viewer', 'Visualizador')], max_length=20, verbose_name='Papel')),
                ('can_create_products', models.BooleanField(default=False, verbose_name='Criar produtos')),
                ('can_edit_products', models.BooleanField(default=False, verbose_name='Editar produtos')),
                ('can_delete_products', models.BooleanField(default=False, verbose_name='Excluir produtos')),
                ('can_view_products', models.BooleanField(default=True, verbose_name='Ver produtos')),
                ('can_create_suppliers', models.BooleanField(default=False, verbose_name='Criar fornecedores')),
                ('can_edit_suppliers', models.BooleanField(default=False, verbose_name='Editar fornecedores')),
                ('can_delete_suppliers', models.BooleanField(default=False, verbose_name='Excluir fornecedores')),
                ('can_view_suppliers', models.BooleanField(default=True, verbose_name='Ver fornecedores')),
                ('can_create_sales', models.BooleanField(default=False, verbose_name='Criar movimentações')),
                ('can_edit_sales', models.BooleanField(default=False, verbose_name='Editar movimentações')),
                ('can_delete_sales', models.BooleanField(default=False, verbose_name='Excluir movimentações')),
                ('can_view_sales', models.BooleanField(default=True, verbose_name='Ver movimentações')),
                ('can_create_reports', models.BooleanField(default=False, verbose_name='Criar relatórios')),
                ('can_view_reports', models.BooleanField(default=True, verbose_name='Ver relatórios')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='Gerenciar usuários')),
                ('can_view_audit_logs', models.BooleanField(default=False, verbose_name='Ver logs de auditoria')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='users.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Papel',
                'verbose_name_plural': 'Papéis',
                'unique_together': {('name', 'company')},
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.role', verbose_name='Papel'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254, verbose_name='Email do usuário')),
                ('action', models.CharField(choices=[('create', 'Criação'), ('update', 'Atualização'), ('delete', 'Exclusão'), ('login', 'Login'), ('logout', 'Logout'), ('view', 'Visualização'), ('export', 'Exportação'), ('import', 'Importação'), ('approve', 'Aprovação'), ('reject', 'Rejeição')], max_length=20, verbose_name='Ação')),
                ('object_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID do objeto')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Representação do objeto')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Mudanças')),
                ('old_values', models.JSONField(blank=True, default=dict, verbose_name='Valores anteriores')),
                ('new_values', models.JSONField(blank=True, default=dict, verbose_name='Novos valores')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Dados extras')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='users.company', verbose_name='Empresa')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Tipo de objeto')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action'], name='users_audit_user_id_c6aa5b_idx'), models.Index(fields=['company', 'created_at'], name='users_audit_company_9a506b_idx'), models.Index(fields=['content_type', 'object_id'], name='users_audit_content_f4c6fb_idx')],
            },
        ),
    ]
