# Generated by Django 4.2.25 on 2025-12-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_category_company_product_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="status",
            field=models.CharField(
                choices=[("ativa", "Ativa"), ("inativa", "Inativa")],
                default="ativa",
                max_length=10,
            ),
        ),
    ]
