# Generated by Django 4.2.25 on 2025-12-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_category_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="batch",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Lote"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="initial_quantity",
            field=models.IntegerField(
                default=1, verbose_name="Quantidade Inicial do Lote"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("ok", "OK"),
                    ("baixo", "Abaixo do Estoque"),
                    ("proximo_vencimento", "Próximo do Vencimento"),
                ],
                default="ok",
                max_length=20,
                verbose_name="Status do Estoque",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads"),
        ),
    ]
