# Generated by Django 4.2.25 on 2025-12-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_batch_product_initial_quantity_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productsupplier",
            unique_together=set(),
        ),
    ]
