# Generated by Django 4.2.25 on 2025-11-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="type",
            field=models.CharField(
                choices=[
                    ("expenses", "Despesas"),
                    ("revenue", "Receitas"),
                    ("full", "Completo"),
                ],
                default="full",
                max_length=8,
            ),
        ),
    ]
