name: first-workflow

# Especifica o gatilho para este fluxo de trabalho. 
# os eventos pushe pull_request, você pode configurar um fluxo de trabalho 
# para ser executado com base nos caminhos de arquivo alterados. 
# Os filtros de caminho não são avaliados para envios de tags.
on: [pull_request]

#Agrupa os trabalhos do fluxo
jobs:
  # Trabalho chamado
  check-pipeline:
    #Propriedade do trabalho

    #Defini o tipo de máquina na qual o trabalho será executado
    #É preciso definir um Executor, podendo ser hospedados no GitHub (mas precisa configurar)
    runs-on: ubuntu-latest

    #Etapas a serem executadas
    steps:

      # Checkout do código
      - name: Check out repository
       # Faz o checkout do repositório para o workspace.
        uses: actions/checkout@v2 

      # Configurar o ambiente de Python 
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  

      # Instala as dependências
      - name: Install dependencies
        # Instalar dependências do arquivo requirements.txt (em Python)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  
        
      # Rodar os testes
      - name: Run tests
        # Executar os testes usando pytest (podendo também ser outro framework de teste)
        run: |
          pytest tests/  
